"""Tests for .env generation, especially template discovery."""

from devready.environment.env_vars import generate_env_file


def test_reads_dotenv_sample_not_just_example(tmp_path):
    # Many repos ship `.env.sample` / `.env.template` instead of `.env.example`.
    (tmp_path / ".env.sample").write_text("API_HOST=localhost\nAPI_KEY=\n")
    path = generate_env_file(tmp_path, interactive=False)
    assert path is not None
    body = path.read_text()
    assert "API_HOST=localhost" in body
    # A secret-looking var with no example value gets a generated value.
    assert "API_KEY=" in body
    key_line = next(l for l in body.splitlines() if l.startswith("API_KEY="))
    assert len(key_line.split("=", 1)[1]) > 0  # not left blank (looks secret)


def test_template_variant_is_used(tmp_path):
    (tmp_path / ".env.template").write_text("PORT=4000\n")
    path = generate_env_file(tmp_path, interactive=False)
    assert path and "PORT=4000" in path.read_text()


def test_existing_env_is_not_overwritten(tmp_path):
    (tmp_path / ".env").write_text("REAL_SECRET=keepme\n")
    (tmp_path / ".env.sample").write_text("FOO=bar\n")
    # Should decline to overwrite a real .env.
    assert generate_env_file(tmp_path, interactive=False) is None
    assert "keepme" in (tmp_path / ".env").read_text()


def test_set_env_values_replaces_in_place_and_appends(tmp_path):
    # The write half of the first-run secrets wizard: replace placeholder
    # lines in place (preserving order and comments), append missing names.
    from devready.environment.env_vars import set_env_values

    env = tmp_path / ".env"
    env.write_text(
        "# Generated by DevReady\n"
        "PORT=3000\n"
        "OPENAI_API_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"
        "DEBUG=false\n"
    )
    written = set_env_values(tmp_path, {
        "OPENAI_API_KEY": "sk-real-key-123",
        "ANTHROPIC_API_KEY": "sk-ant-456",
    })
    assert sorted(written) == ["ANTHROPIC_API_KEY", "OPENAI_API_KEY"]
    body = env.read_text()
    lines = body.splitlines()
    assert "# Generated by DevReady" in lines[0]          # comments preserved
    assert lines[1] == "PORT=3000"                        # order preserved
    assert lines[2] == "OPENAI_API_KEY=sk-real-key-123"   # replaced in place
    assert lines[3] == "DEBUG=false"
    assert "ANTHROPIC_API_KEY=sk-ant-456" in body         # appended


def test_set_env_values_rejects_bad_names_and_multiline(tmp_path):
    from devready.environment.env_vars import set_env_values

    (tmp_path / ".env").write_text("A=1\n")
    written = set_env_values(tmp_path, {
        "BAD NAME": "x",              # space in name
        "INJECT": "evil\nEXTRA=1",    # multi-line value
        "": "x",
        "GOOD_KEY": "value",
    })
    assert written == ["GOOD_KEY"]
    body = (tmp_path / ".env").read_text()
    assert "EXTRA=1" not in body and "BAD NAME" not in body


def test_set_env_values_clears_pending_placeholder(tmp_path):
    # End-to-end for the wizard: a placeholder key is pending; after the user
    # saves a real value it is no longer flagged.
    from devready.environment.env_vars import (
        generate_env_file, has_placeholder_api_keys, set_env_values,
    )

    (tmp_path / ".env.example").write_text("OPENAI_API_KEY=\n")
    generate_env_file(tmp_path, interactive=False)
    assert has_placeholder_api_keys(tmp_path / ".env") == ["OPENAI_API_KEY"]
    set_env_values(tmp_path, {"OPENAI_API_KEY": "sk-proj-realkey"})
    assert has_placeholder_api_keys(tmp_path / ".env") == []


def test_key_help_url_known_and_unknown():
    from devready.environment.env_vars import key_help_url

    assert "openai.com" in key_help_url("OPENAI_API_KEY")
    assert key_help_url("SOME_RANDOM_TOKEN") == ""


def test_set_env_values_handles_bom(tmp_path):
    # Windows tools (Notepad, PowerShell Set-Content) write .env with a UTF-8
    # BOM; the first variable's name then reads as "﻿NAME" and dodged the
    # in-place replace, silently APPENDING a duplicate line — seen live.
    from devready.environment.env_vars import (
        has_placeholder_api_keys, set_env_values,
    )

    env = tmp_path / ".env"
    env.write_bytes(("﻿OPENAI_API_KEY=" + "a" * 48 + "\nPORT=3000\n").encode("utf-8"))
    assert has_placeholder_api_keys(env) == ["OPENAI_API_KEY"]  # BOM stripped
    set_env_values(tmp_path, {"OPENAI_API_KEY": "sk-real"})
    body = env.read_text(encoding="utf-8")
    assert body.count("OPENAI_API_KEY") == 1                    # replaced, not duplicated
    assert "OPENAI_API_KEY=sk-real" in body
